server:
  port: 8001
spring :
  application:
    name: acvitivi
  #data source config
  datasource :
    username: root
    password : 123456
    url: jdbc:mysql://127.0.0.1:3306/activiti?useUnicode=true&characterEncoding=utf8&useSSL=false&allowMultiQueries=true&serverTimezone=UTC
    driver-class-name: com.mysql.jdbc.Driver